Start of fetching myfriends feature
friend.module:
- added forwardRef to avoid circular
dependency error between mutually
importing modules.

friend.service:
- creation of  getAllFriendsByUserId()
method to retrieve all friends of a given
user

user.controller:
- renaming the endpoint
'GET api/user/user/me' to 'GET
api/user/getmyinfo'

- shifting logic from
GET api/user/user/getmyinfo endpoint to
user.service.getMyInfo() method

- creation of the 'GET api/user/getmyfriends'
endpoint in charge of retrieving the
user's friends list using the
userService.getMyFriends() method

user.module:
- added forwardRef to avoid
circular dependency error between mutually
importing modules

- provider aggregation

user.service:
- creation of getMyInfo()
method which is used by the endpoint 'GET
api/user/getmyinfo'

- creation of the
getMyFriends() method used by the 'GET
api/user/getmyfriends' endpoint

Main.Profile:
- update of the endpoint to
be fetched to be consistent with the
rename done in the backend

Solving a dependency problem

Error: 'Nest can't resolve dependencies of
the FriendService (FriendRepository, ?)'