frontend: change ctx type
Why?
because when we build the frontend we
receive this error:
```
src/components/pong/BoardGame.tsx(60,13): error TS2322: Type 'CanvasRenderingContext2D | null' is not assignable to type 'CanvasRenderingContext2D'.
  Type 'null' is not assignable to type 'CanvasRenderingContext2D'.
```